### ISSUE TITLE
Unable to install node modules in Mac machine

### ISSUE THREAD

**Issue by AlinaThomas** [hcl-dx/WebDevToolkitForDx#23]
Did the following steps on my Mac system:
1. I installed node with version v16.13.0
2. I downloaded and extracted the folder. 
3. Went to the respective folder (cd WebDevToolkitForDx-master)
4. On running 'npm install -g' im getting the following message (Please see attached image)
     Tried running 'sudo npm install -g' still getting the same messsage.
5. Even tried 'sudo chown -R $USER /usr/local/lib/node_modules' 

Node modules folder was not installed within the folder structure.

<img width="1024" alt="Screenshot 2021-12-07 at 5 12 10 PM" src="https://user-images.githubusercontent.com/37771369/145026115-cf03d243-c01e-4d9b-9a0a-5e99e8630f7e.png">

Any suggestions or fixes would be greatly appreciated. Thanks

**Comment by ThomasHurek** [comment]
We have tested with node 12 but not node 16. Could you try with node 12 to see if that solves the issue?

**Comment by ikedatdoc** [comment]
Thanks. I was able to install using node 12.
